-- partner_mylinks 테이블 생성 SQL
-- Supabase SQL Editor에서 이 쿼리를 실행하세요

-- 테이블 생성
create table if not exists public.partner_mylinks (
  id bigint generated by default as identity primary key,
  partner_id text not null,
  "from" text not null,
  "to" text not null,
  departure_date date not null,
  return_date date not null,
  trip_days int,
  nonstop boolean default false,
  booking_url text not null, -- 원본 예약 URL
  mylink text not null, -- 변환된 마이링크
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint partner_mylinks_unique unique(partner_id, "from", "to", departure_date, return_date, trip_days, nonstop)
);

-- 인덱스 생성
create index if not exists idx_partner_mylinks_lookup on public.partner_mylinks (partner_id, "from", "to", departure_date, return_date, trip_days, nonstop);
create index if not exists idx_partner_mylinks_partner on public.partner_mylinks (partner_id);

-- 생성 확인
SELECT '테이블 생성 완료!' as message, COUNT(*) as row_count FROM public.partner_mylinks;

