CREATE TABLE IF NOT EXISTS public.partner_mylink_stats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id text NOT NULL,
  date date NOT NULL,
  count int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT partner_mylink_stats_unique UNIQUE(partner_id, date)
);

CREATE INDEX IF NOT EXISTS idx_partner_stats_lookup 
  ON public.partner_mylink_stats (partner_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_partner_stats_partner 
  ON public.partner_mylink_stats (partner_id);

CREATE OR REPLACE FUNCTION increment_mylink_count(
  p_partner_id text,
  p_date date
) RETURNS void AS $$
BEGIN
  INSERT INTO partner_mylink_stats (partner_id, date, count, updated_at)
  VALUES (p_partner_id, p_date, 1, NOW())
  ON CONFLICT (partner_id, date)
  DO UPDATE SET 
    count = partner_mylink_stats.count + 1,
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

SELECT '테이블 생성 완료' as message;
SELECT increment_mylink_count('test-partner', CURRENT_DATE);
SELECT * FROM partner_mylink_stats WHERE partner_id = 'test-partner';


