export interface CityItem { nameKo: string; code: string; region: string }

// 서버리스 배포용 전체 목적지 목록 (server/cities.ts와 동일하게 유지)
export const DESTINATIONS_ALL: CityItem[] = [
  // 일본(아시아)
  { nameKo: "도쿄", code: "TYO", region: "아시아" },
  { nameKo: "오사카", code: "OSA", region: "아시아" },
  { nameKo: "후쿠오카", code: "FUK", region: "아시아" },
  { nameKo: "삿포로", code: "SPK", region: "아시아" },
  { nameKo: "오키나와", code: "OKA", region: "아시아" },
  { nameKo: "오사카/고베", code: "UKB", region: "아시아" },
  { nameKo: "나고야", code: "NGO", region: "아시아" },
  { nameKo: "구마모토", code: "KMJ", region: "아시아" },
  { nameKo: "기타큐슈", code: "KKJ", region: "아시아" },
  { nameKo: "다카마쓰", code: "TAK", region: "아시아" },
  { nameKo: "오이타", code: "OIT", region: "아시아" },
  { nameKo: "마쓰야마", code: "MYJ", region: "아시아" },
  { nameKo: "히로시마", code: "HIJ", region: "아시아" },
  { nameKo: "요나고", code: "YGJ", region: "아시아" },

  // 아시아
  { nameKo: "다낭", code: "DAD", region: "아시아" },
  { nameKo: "방콕/수완나품", code: "BKK", region: "아시아" },
  { nameKo: "세부", code: "CEB", region: "아시아" },
  { nameKo: "싱가포르", code: "SIN", region: "아시아" },
  { nameKo: "코타키나발루", code: "BKI", region: "아시아" },
  { nameKo: "나트랑/깜란", code: "CXR", region: "아시아" },
  { nameKo: "홍콩", code: "HKG", region: "아시아" },
  { nameKo: "호치민", code: "SGN", region: "아시아" },
  { nameKo: "대만/타오위안", code: "TPE", region: "아시아" },
  { nameKo: "치앙마이", code: "CNX", region: "아시아" },
  { nameKo: "울란바토르", code: "ULN", region: "아시아" },
  { nameKo: "하노이", code: "HAN", region: "아시아" },
  { nameKo: "푸켓", code: "HKT", region: "아시아" },
  { nameKo: "마닐라", code: "MNL", region: "아시아" },
  { nameKo: "대만/송산", code: "TSA", region: "아시아" },
  { nameKo: "마카오", code: "MFM", region: "아시아" },
  { nameKo: "프놈펜", code: "PNH", region: "아시아" },
  { nameKo: "알마티", code: "ALA", region: "아시아" },
  { nameKo: "쿠알라룸푸르", code: "KUL", region: "아시아" },
  { nameKo: "몰디브/말레", code: "MLE", region: "아시아" },

  // 미주
  { nameKo: "하와이/호놀룰루", code: "HNL", region: "미주" },
  { nameKo: "로스앤젤레스", code: "LAX", region: "미주" },
  { nameKo: "뉴욕", code: "NYC", region: "미주" },
  { nameKo: "샌프란시스코", code: "SFO", region: "미주" },
  { nameKo: "라스베이거스", code: "LAS", region: "미주" },
  { nameKo: "댈러스", code: "DFW", region: "미주" },
  { nameKo: "밴쿠버", code: "YVR", region: "미주" },
  { nameKo: "토론토", code: "YTO", region: "미주" },
  { nameKo: "워싱턴/덜레스", code: "IAD", region: "미주" },
  { nameKo: "캘거리", code: "YYC", region: "미주" },

  // 유럽
  { nameKo: "파리", code: "PAR", region: "유럽" },
  { nameKo: "런던", code: "LON", region: "유럽" },
  { nameKo: "로마", code: "ROM", region: "유럽" },
  { nameKo: "바르셀로나", code: "BCN", region: "유럽" },
  { nameKo: "프랑크푸르트", code: "FRA", region: "유럽" },
  { nameKo: "프라하", code: "PRG", region: "유럽" },
  { nameKo: "암스테르담", code: "AMS", region: "유럽" },
  { nameKo: "이스탄불", code: "IST", region: "유럽" },
  { nameKo: "헬싱키", code: "HEL", region: "유럽" },
  { nameKo: "취리히", code: "ZRH", region: "유럽" },
  { nameKo: "바르샤바", code: "WAW", region: "유럽" },
  { nameKo: "리스본", code: "LIS", region: "유럽" },
  { nameKo: "밀라노/말펜사", code: "MXP", region: "유럽" },
  { nameKo: "부다페스트", code: "BUD", region: "유럽" },
  { nameKo: "자그레브", code: "ZAG", region: "유럽" },
  { nameKo: "두브로브니크", code: "DBV", region: "유럽" },
  { nameKo: "베니스", code: "VCE", region: "유럽" },
  { nameKo: "비엔나", code: "VIE", region: "유럽" },

  // 대양주
  { nameKo: "괌", code: "GUM", region: "대양주" },
  { nameKo: "사이판", code: "SPN", region: "대양주" },
  { nameKo: "시드니", code: "SYD", region: "대양주" },
  { nameKo: "멜버른", code: "MEL", region: "대양주" },

  // 중동
  { nameKo: "아부다비", code: "AUH", region: "중동" },
  { nameKo: "텔아비브", code: "TLV", region: "중동" },
  { nameKo: "도하", code: "DOH", region: "중동" },
  { nameKo: "두바이", code: "DXB", region: "중동" },

  // 중남미
  { nameKo: "상파울로", code: "GRU", region: "중남미" },
  { nameKo: "칸쿤", code: "CUN", region: "중남미" },
  { nameKo: "산티아고", code: "SCL", region: "중남미" },
  { nameKo: "하바나", code: "HAV", region: "중남미" },

  // 아프리카
  { nameKo: "나이로비", code: "NBO", region: "아프리카" },
  { nameKo: "케이프타운", code: "CPT", region: "아프리카" },
  { nameKo: "카이로", code: "CAI", region: "아프리카" },
  { nameKo: "모리셔스", code: "MRU", region: "아프리카" },

  // 중국(아시아)
  { nameKo: "북경", code: "BJS", region: "아시아" },
  { nameKo: "상해/푸동", code: "PVG", region: "아시아" },
  { nameKo: "청도", code: "TAO", region: "아시아" },
  { nameKo: "청두", code: "CTU", region: "아시아" },
  
  // 추가: 인기/수도 확장 (아시아 - 일본 제외)
  { nameKo: "코사무이", code: "USM", region: "아시아" },
  { nameKo: "끄라비", code: "KBV", region: "아시아" },
  { nameKo: "치앙라이", code: "CEI", region: "아시아" },
  { nameKo: "파타야/우타파오", code: "UTP", region: "아시아" },
  { nameKo: "푸꾸옥", code: "PQC", region: "아시아" },
  { nameKo: "달랏", code: "DLI", region: "아시아" },
  { nameKo: "후에", code: "HUI", region: "아시아" },
  { nameKo: "하이퐁", code: "HPH", region: "아시아" },
  { nameKo: "보라카이/칼리보", code: "KLO", region: "아시아" },
  { nameKo: "보라카이/카틱란", code: "MPH", region: "아시아" },
  { nameKo: "클락", code: "CRK", region: "아시아" },
  { nameKo: "보홀", code: "TAG", region: "아시아" },
  { nameKo: "푸에르토프린세사", code: "PPS", region: "아시아" },
  { nameKo: "랑카위", code: "LGK", region: "아시아" },
  { nameKo: "페낭", code: "PEN", region: "아시아" },
  { nameKo: "조호르바루", code: "JHB", region: "아시아" },
  { nameKo: "쿠칭", code: "KCH", region: "아시아" },
  { nameKo: "발리/덴파사르", code: "DPS", region: "아시아" },
  { nameKo: "자카르타", code: "CGK", region: "아시아" },
  { nameKo: "롬복", code: "LOP", region: "아시아" },
  { nameKo: "라부안바조", code: "LBJ", region: "아시아" },
  { nameKo: "수라바야", code: "SUB", region: "아시아" },
  { nameKo: "욕야카르타", code: "JOG", region: "아시아" },
  { nameKo: "가오슝", code: "KHH", region: "아시아" },
  { nameKo: "타이중", code: "RMQ", region: "아시아" },
  { nameKo: "타이난", code: "TNN", region: "아시아" },
  { nameKo: "씨엠립", code: "REP", region: "아시아" },
  { nameKo: "비엔티안", code: "VTE", region: "아시아" },
  { nameKo: "루앙프라방", code: "LPQ", region: "아시아" },
  { nameKo: "양곤", code: "RGN", region: "아시아" },
  { nameKo: "아스타나", code: "NQZ", region: "아시아" },

  // 추가: 중국(아시아)
  { nameKo: "광저우", code: "CAN", region: "아시아" },
  { nameKo: "선전", code: "SZX", region: "아시아" },
  { nameKo: "항저우", code: "HGH", region: "아시아" },
  { nameKo: "시안", code: "XIY", region: "아시아" },
  { nameKo: "샤먼", code: "XMN", region: "아시아" },
  { nameKo: "다롄", code: "DLC", region: "아시아" },
  { nameKo: "선양", code: "SHE", region: "아시아" },
  { nameKo: "하얼빈", code: "HRB", region: "아시아" },
  { nameKo: "난징", code: "NKG", region: "아시아" },
  { nameKo: "쿤밍", code: "KMG", region: "아시아" },
  { nameKo: "우한", code: "WUH", region: "아시아" },
  { nameKo: "충칭", code: "CKG", region: "아시아" },
  { nameKo: "톈진", code: "TSN", region: "아시아" },
  { nameKo: "창사", code: "CSX", region: "아시아" },
  { nameKo: "정저우", code: "CGO", region: "아시아" },
  { nameKo: "닝보", code: "NGB", region: "아시아" },
  { nameKo: "푸저우", code: "FOC", region: "아시아" },
  { nameKo: "원저우", code: "WNZ", region: "아시아" },
  { nameKo: "난닝", code: "NNG", region: "아시아" },

  // 추가: 일본
  { nameKo: "이시가키", code: "ISG", region: "아시아" },
  { nameKo: "미야코", code: "MMY", region: "아시아" },
  { nameKo: "센다이", code: "SDJ", region: "아시아" },
  { nameKo: "시즈오카", code: "FSZ", region: "아시아" },
  { nameKo: "가고시마", code: "KOJ", region: "아시아" },
  { nameKo: "미야자키", code: "KMI", region: "아시아" },
  { nameKo: "오카야마", code: "OKJ", region: "아시아" },
  { nameKo: "나가사키", code: "NGS", region: "아시아" },
  { nameKo: "아사히카와", code: "AKJ", region: "아시아" },
  { nameKo: "아오모리", code: "AOJ", region: "아시아" },
  { nameKo: "하코다테", code: "HKD", region: "아시아" },
  { nameKo: "오비히로", code: "OBO", region: "아시아" },
  { nameKo: "고마츠", code: "KMQ", region: "아시아" },
  { nameKo: "도야마", code: "TOY", region: "아시아" },
  { nameKo: "니가타", code: "KIJ", region: "아시아" },
  { nameKo: "고치", code: "KCZ", region: "아시아" },

  // 추가: 미주(미국/캐나다)
  { nameKo: "시애틀", code: "SEA", region: "미주" },
  { nameKo: "시카고", code: "CHI", region: "미주" },
  { nameKo: "애틀랜타", code: "ATL", region: "미주" },
  { nameKo: "보스턴", code: "BOS", region: "미주" },
  { nameKo: "마이애미", code: "MIA", region: "미주" },
  { nameKo: "휴스턴", code: "IAH", region: "미주" },
  { nameKo: "덴버", code: "DEN", region: "미주" },
  { nameKo: "샌디에이고", code: "SAN", region: "미주" },
  { nameKo: "포틀랜드", code: "PDX", region: "미주" },
  { nameKo: "필라델피아", code: "PHL", region: "미주" },
  { nameKo: "피닉스", code: "PHX", region: "미주" },
  { nameKo: "올랜도", code: "MCO", region: "미주" },
  { nameKo: "몬트리올", code: "YMQ", region: "미주" },
  { nameKo: "오타와", code: "YOW", region: "미주" },
  { nameKo: "에드먼턴", code: "YEG", region: "미주" },
  { nameKo: "위니펙", code: "YWG", region: "미주" },
  { nameKo: "퀘벡시티", code: "YQB", region: "미주" },

  // 추가: 유럽
  { nameKo: "마드리드", code: "MAD", region: "유럽" },
  { nameKo: "뮌헨", code: "MUC", region: "유럽" },
  { nameKo: "베를린", code: "BER", region: "유럽" },
  { nameKo: "아테네", code: "ATH", region: "유럽" },
  { nameKo: "니스", code: "NCE", region: "유럽" },
  { nameKo: "코펜하겐", code: "CPH", region: "유럽" },
  { nameKo: "스톡홀름", code: "ARN", region: "유럽" },
  { nameKo: "오슬로", code: "OSL", region: "유럽" },
  { nameKo: "브뤼셀", code: "BRU", region: "유럽" },
  { nameKo: "제네바", code: "GVA", region: "유럽" },
  { nameKo: "뒤셀도르프", code: "DUS", region: "유럽" },
  { nameKo: "함부르크", code: "HAM", region: "유럽" },
  { nameKo: "슈투트가르트", code: "STR", region: "유럽" },
  { nameKo: "크라쿠프", code: "KRK", region: "유럽" },
  { nameKo: "더블린", code: "DUB", region: "유럽" },
  { nameKo: "맨체스터", code: "MAN", region: "유럽" },
  { nameKo: "에든버러", code: "EDI", region: "유럽" },
  { nameKo: "버밍엄", code: "BHX", region: "유럽" },
  { nameKo: "포르투", code: "OPO", region: "유럽" },
  { nameKo: "말라가", code: "AGP", region: "유럽" },
  { nameKo: "팔마데마요르카", code: "PMI", region: "유럽" },
  { nameKo: "나폴리", code: "NAP", region: "유럽" },
  { nameKo: "피렌체", code: "FLR", region: "유럽" },
  { nameKo: "안탈리아", code: "AYT", region: "유럽" },
  { nameKo: "산토리니", code: "JTR", region: "유럽" },
  { nameKo: "미코노스", code: "JMK", region: "유럽" },

  // 추가: 대양주
  { nameKo: "브리즈번", code: "BNE", region: "대양주" },
  { nameKo: "골드코스트", code: "OOL", region: "대양주" },
  { nameKo: "퍼스", code: "PER", region: "대양주" },
  { nameKo: "애들레이드", code: "ADL", region: "대양주" },
  { nameKo: "오클랜드", code: "AKL", region: "대양주" },
  { nameKo: "크라이스트처치", code: "CHC", region: "대양주" },
  { nameKo: "케언즈", code: "CNS", region: "대양주" },

  // 추가: 중동
  { nameKo: "리야드", code: "RUH", region: "중동" },
  { nameKo: "제다", code: "JED", region: "중동" },
  { nameKo: "무스카트", code: "MCT", region: "중동" },
  { nameKo: "바레인", code: "BAH", region: "중동" },
  { nameKo: "쿠웨이트", code: "KWI", region: "중동" },
  { nameKo: "테헤란", code: "IKA", region: "중동" },
  { nameKo: "암만", code: "AMM", region: "중동" },

  // 추가: 남아시아(지역값: 아시아)
  { nameKo: "델리", code: "DEL", region: "아시아" },
  { nameKo: "뭄바이", code: "BOM", region: "아시아" },
  { nameKo: "첸나이", code: "MAA", region: "아시아" },
  { nameKo: "벵갈루루", code: "BLR", region: "아시아" },
  { nameKo: "하이데라바드", code: "HYD", region: "아시아" },
  { nameKo: "코치", code: "COK", region: "아시아" },
  { nameKo: "트리반드룸", code: "TRV", region: "아시아" },
  { nameKo: "고아", code: "GOI", region: "아시아" },
  { nameKo: "콜롬보", code: "CMB", region: "아시아" },
  { nameKo: "카트만두", code: "KTM", region: "아시아" },
  { nameKo: "다카", code: "DAC", region: "아시아" },

  // 추가: 중남미
  { nameKo: "멕시코시티", code: "MEX", region: "중남미" },
  { nameKo: "리마", code: "LIM", region: "중남미" },
  { nameKo: "리우데자네이루", code: "GIG", region: "중남미" },
  { nameKo: "부에노스아이레스", code: "EZE", region: "중남미" },
  { nameKo: "보고타", code: "BOG", region: "중남미" },
  { nameKo: "파나마시티", code: "PTY", region: "중남미" },

  // 추가: 아프리카
  { nameKo: "요하네스버그", code: "JNB", region: "아프리카" },
  { nameKo: "마라케시", code: "RAK", region: "아프리카" },
  { nameKo: "카사블랑카", code: "CMN", region: "아프리카" },
  { nameKo: "잔지바르", code: "ZNZ", region: "아프리카" },
  { nameKo: "아디스아바바", code: "ADD", region: "아프리카" },
  { nameKo: "마헤/세이셸", code: "SEZ", region: "아프리카" },
];


