name: Scan fares (all + direct)
on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: {}
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Scan all (transfer=-1)
        run: npx -y tsx scripts/scan-all.ts
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SCAN_FROM: ICN
          SCAN_DAYS: 30
          SCAN_MIN_DAYS: 3
          SCAN_MAX_DAYS: 7
          SCAN_CONCURRENCY: 4
          SCAN_TRANSFER: -1

  direct:
    runs-on: ubuntu-latest
    needs: all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Scan direct only (transfer=0)
        run: npx -y tsx scripts/scan-all.ts
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SCAN_FROM: ICN
          SCAN_DAYS: 30
          SCAN_MIN_DAYS: 3
          SCAN_MAX_DAYS: 7
          SCAN_CONCURRENCY: 4
          SCAN_TRANSFER: 0


